title: Vinprovningsguide
description: En guide till typiska viner baserat på druvsort.
theme: minima

# URL settings
url: "https://LinusdP.github.io"
baseurl: "/Vinprovning"

# Jekyll configuration
markdown: kramdown
header_pages:
  - grapes/pinot_noir.md
  - grapes/gamay.md
  - grapes/nebbiolo.md
  - grapes/merlot.md
  - grapes/syrah.md
  - grapes/cabernet_sauvignon.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
